# Site settings ...
uri: zaolin.github.io
url: https://zaolin.github.io
name: Zaolin
title: A hackers daily blog
email: zaolin@das-labor.org
author: zaolin
baseurl: ""
timezone: Europe/Amsterdam
keywords: "Diki Andriansyah, Diki Andriansyah Blog, dikiaap, Diki Andriansyah Ananta Putra"
description: "Hi! Saya Diki Andriansyah. Suka membangun sesuatu dengan code dan bekerja sebagai developer. Brom [] ini adalah sebuah blog room dan banyak bermacam-macam aktifitas yang saya tulis di sini."
social_username: zaolin

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: "write/:year/:month/:day/:title/"
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
