# Site settings ...
uri: zaolin.github.io
url: https://zaolin.github.io
name: Zaolin
title: A hackers daily blog
email: zaolin@das-labor.org
author: zaolin
baseurl: ""
timezone: Europe/Amsterdam
keywords: "Coreboot, Trusted Computing, Gentoo, IT Security, Cryptography"
description: "Fo"
social_username: zaolin
secondary_social_username: _zaolin_

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: "write/:year/:month/:day/:title/"
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
